blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/DynamicEndpoints/espn-mcp/blob/main/README.md
    about: Read the full documentation and examples
  - name: 💬 Discussions
    url: https://github.com/DynamicEndpoints/espn-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 ESPN API Status
    url: https://site.api.espn.com/apis/site/v2/sports
    about: Check ESPN API status and endpoints